# https://hub.docker.com/r/google/dart
image: google/dart:latest

variables:
  PUB_VARS: "--platform vm --timeout 30s --concurrency=6 --test-randomize-ordering-seed=random --reporter=expanded"

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .pub-cache/global_packages

before_script:
  - export PATH="$PATH":"~/.pub-cache/bin"
  - pub get --no-precompile

style_check:
  stage: test
  script:
    - dart format -o none --set-exit-if-changed .

lint:
  stage: test
  script:
    - dart analyze .

test:
  stage: test
  script:
    - dart test $PUB_VARS
