name: dart_wot
description: A W3C Web of Things implementation written in Dart. Supports interacting with Things using CoAP, HTTP, and MQTT.
version: 0.26.0
homepage: https://github.com/namib-project/dart_wot

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  build_runner: ^2.3.0
  coverage: ^1.0.4
  dart_code_metrics: ^5.4.0
  lint: ^2.0.1
  lints: ^2.0.1
  mockito: ^5.0.17
  test: ^1.16.0

dependencies:
  cbor: ^5.1.2
  coap: ^8.0.0
  collection: ^1.16.0
  curie: ^0.1.0
  dcaf: ^0.1.0
  http: ^0.13.4
  http_auth: ^1.0.1
  http_parser: ^4.0.0
  json_schema3: ^1.0.0
  meta: ^1.8.0
  mqtt_client: ^9.7.4
  multicast_dns: ^0.3.2+1
  typed_data: ^1.3.0
  uri: ^1.0.0
  uuid: ^3.0.7
